# Generated by Django 3.2.9 on 2021-12-04 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Codigo', models.CharField(max_length=10)),
                ('Slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(db_index=True, max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('EnStock', models.BooleanField(default=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Slug', models.SlugField(max_length=255)),
                ('Foto', models.ImageField(upload_to='images/')),
                ('Descripcion', models.TextField(blank=True)),
                ('FechaCreacion', models.DateField(auto_now_add=True)),
                ('FechaActualizacion', models.DateField(auto_now=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='main.categoria')),
                ('CreadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_producto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'productos',
                'ordering': ['-FechaCreacion'],
            },
        ),
    ]
